name: Release Workflow

on:
  push:
    branches:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for git describe --tags

      - name: Get version from branch name
        id: version
        run: |
          VERSION=$(echo "${GITHUB_REF#refs/heads/v}")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Install git-chglog
        run: |
          curl -sSfL https://raw.githubusercontent.com/git-chglog/git-chglog/master/install.sh | sh -s -- -b $HOME/.local/bin

      - name: Generate Changelog
        run: |
          $HOME/.local/bin/git-chglog > CHANGELOG.md
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: Release ${{ steps.version.outputs.VERSION }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Setup Rust Toolchain
        uses: actions/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build Linux Binary
        run: |
          cargo build --release
          mv target/release/panther panther-linux

      - name: Upload Linux Binary to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./panther-linux
          asset_name: panther-linux
          asset_content_type: application/octet-stream
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust Toolchain
        uses: actions/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build Windows Binary
        run: |
          cargo build --release --target x86_64-pc-windows-gnu
          mv target/x86_64-pc-windows-gnu/release/panther.exe panther-windows.exe

      - name: Upload Windows Binary to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./panther-windows.exe
          asset_name: panther-windows.exe
          asset_content_type: application/octet-stream
    needs: release
